// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPc7FqgRSI6bcP18aIxHmzk-yzQJp6AKs',
    appId: '1:738197946630:web:966241d8521234416c9e87',
    messagingSenderId: '738197946630',
    projectId: 'furlo-e4473',
    authDomain: 'furlo-e4473.firebaseapp.com',
    storageBucket: 'furlo-e4473.firebasestorage.app',
    measurementId: 'G-N1H62GYV3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB868AaYoItpG183vlM7WfmGzc49oFLaJI',
    appId: '1:738197946630:android:13087fd32922fec76c9e87',
    messagingSenderId: '738197946630',
    projectId: 'furlo-e4473',
    storageBucket: 'furlo-e4473.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYc-V5XydZOuFJ64OonSAsqn63qoinDc',
    appId: '1:738197946630:ios:0d5ee6c469685e316c9e87',
    messagingSenderId: '738197946630',
    projectId: 'furlo-e4473',
    storageBucket: 'furlo-e4473.firebasestorage.app',
    iosClientId:
        '738197946630-7qq158soc5ca7iigfhsgbf18pgduieg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.furlo',
  );
}
